---

- name: add repository
  shell: wget https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb && sudo dpkg -i erlang-solutions_1.0_all.deb
  become: yes

- name: install erlang and elixir
  apt:
    name: "{{ item }}"
    update_cache: true
  with_items:
    - esl-erlang
    - elixir