---
- set_fact:
    vnctools:  
      - expect
      - xclip
      - xfce4
      - xfce4-goodies
      # VSCOODE live share reqs
      - libssl1.0.0 
      - libkrb5-3
      - zlib1g
      - libicu60
      - gnome-keyring
      - libsecret-1-0
      - desktop-file-utils
      - x11-utils
      - tigervnc-standalone-server

- name: Install vnctools
  package: name="{{ item }}" state=present
  with_items:
    - "{{ vnctools|default([]) }}"

- name: Copy password script
  template: src=create_password.j2 dest=/tmp/pass.sh mode=0744 owner="{{ user }}" group="{{ user }}"
  tags:
    - vnc

- name: Creates vnc directory
  file:
    path: "/home/{{ user }}/.vnc"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
  tags:
    - vnc

- name: Run password script
  shell: . /tmp/pass.sh
  become_user: "{{ user }}"

- name: Copy xstartup script
  template: src=xstartup.j2 dest="/home/{{ user }}/.vnc/xstartup" mode=0744 owner="{{ user }}" group="{{ user }}"
  tags:
    - vnc

- name: export display in ~/.zshrc
  lineinfile:
    dest: "/home/{{ user }}/.zshrc"
    line: "export DISPLAY=:{{ vnc_display_no }}"
    create: yes
  become_user: "{{ user }}"
  tags: vnc

- name: vncserver | template /etc/systemd/system/vncserver.service
  template: src=systemd.conf.j2 dest=/etc/systemd/system/vncserver.service owner=root group=root mode=0755
  become: yes
  notify: restart vncserver
  tags:
    - vnc
