---
- name: Configure the server and install required software
  hosts: all
  gather_facts: false
  become: true
  vars_files:
    - config.cfg

  roles:
    - role: common
      tags: common
    - role: zsh
      tags: zsh
    - role: docker
      tags: docker
    - role: vnc-server
      tags: vnc
    - role: vscode
      tags: vscode
    - role: code-server
      tags: code-server
    - role: nginx
      tags: code-server
    - role: chrome
      tags: chrome
    - role: nvm
      tags: tools
    - role: elixir
      tags: langs
    - role: golang
      tags: langs
    - role: scm-breeze
      tags: tools
