---
- name: Configure the server and install required software
  hosts: all
  gather_facts: false
  become: true
  vars_files:
    - config.cfg

  roles:
    - role: common
      tags: common
    - role: zsh
      tags: zsh
    - role: docker
      tags: docker
    - role: vscode
      tags: vscode
    - role: chrome
      tags: chrome
    - role: nvm
      tags: tools
    - role: vnc-server
      tags: vnc
