---

- name: set gpg key
  apt_key:
    url: "https://packages.microsoft.com/keys/microsoft.asc"
    state: present

- name: add repository
  apt_repository:
    repo: 'deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main'
    filename: vscode
    state: present
    update_cache: yes

- name: install vscode
  apt:
    name: code
    update_cache: true
  when:
    - vscode_install

- name: install vscode extensions
  shell: code --install-extension {{ item }}
  with_items: "{{ extensions }}"
  become: true
  become_user: "{{ user }}"

- name: write settings for vscode
  template:
    src: settings.json.j2
    dest: "/home/{{ user }}/.config/Code/User/settings.json"