---
- block:
  - name: Check the system
    raw: uname -a
    register: OS
    tags:
      - update-users

  - include_tasks: ubuntu.yml
    when: '"Ubuntu" in OS.stdout or "Linux" in OS.stdout'
    tags:
      - update-users

  - name: Sysctl tuning
    sysctl: name="{{ item.item }}" value="{{ item.value }}"
    when: item.item != ""
    with_items:
      - "{{ sysctl|default([]) }}"
    tags:
      - always

  - name: Create a login user
    user:
      name: "{{ user }}"
      password: "{{ password | password_hash('sha512') }}"
      groups: # Empty by default, here we give it some groups
      - sudo
      state: present
      shell: /bin/bash       # Defaults to /bin/bash
      createhome: yes        # Defaults to yes


  - meta: flush_handlers
  rescue:
    - debug: var=fail_hint
      tags: always
    - fail:
      tags: always
