---
- name: Gather facts
  setup:

- name: Cloud only tasks
  block:
    - name: Install software updates
      apt:
        update_cache: true
        install_recommends: true
        upgrade: dist

    - name: Check if reboot is required
      shell: >
        if [[ -e /var/run/reboot-required ]]; then echo "required"; else echo "no"; fi
      args:
        executable: /bin/bash
      register: reboot_required

    - name: Reboot
      shell: sleep 2 && shutdown -r now "Ansible updates triggered"
      async: 1
      poll: 0
      when: reboot_required is defined and reboot_required.stdout == 'required'
      ignore_errors: true

    - name: Wait until SSH becomes ready...
      local_action:
        module: wait_for
        port: 22
        host: "{{ inventory_hostname }}"
        search_regex: OpenSSH
        delay: 10
        timeout: 320
      when: reboot_required is defined and reboot_required.stdout == 'required'
      become: false
  when: provider != "local"

- name: Include unatteded upgrades configuration
  import_tasks: unattended-upgrades.yml

- name: Disable MOTD on login and SSHD
  replace: dest="{{ item.file }}" regexp="{{ item.regexp }}" replace="{{ item.line }}"
  with_items:
    - { regexp: '^session.*optional.*pam_motd.so.*', line: '# MOTD DISABLED', file: '/etc/pam.d/login' }
    - { regexp: '^session.*optional.*pam_motd.so.*', line: '# MOTD DISABLED', file: '/etc/pam.d/sshd' }

- set_fact:
    tools:
      - build-essential
      - xfce4
      - xfce4-goodies
      - screen
      - mosh
      - git
      - expect
      - xclip
      - tig
      # VSCOODE live share reqs
      - libssl1.0.0 
      - libkrb5-3
      - zlib1g
      - libicu60
      - gnome-keyring
      - libsecret-1-0
      - desktop-file-utils
      - x11-utils
      - neovim
      - python-neovim
      - python3-neovim
      - fonts-inconsolata
    sysctl:
      - item: fs.inotify.max_user_watches
        value: 524288

- name: Install tools
  package: name="{{ item }}" state=present
  with_items:
    - "{{ tools|default([]) }}"
