---
- name: Git clone scm_breeze
  git:
    repo: 'https://github.com/scmbreeze/scm_breeze.git'
    dest: "/home/{{ user }}/.scm_breeze"
  become_user: "{{ user }}"

- name: Run install script
  shell: "/home/{{ user }}/.scm_breeze/install.sh"
  become_user: "{{ user }}"