---
  
- name: install code-server to lib dir
  unarchive:
    src: "{{ code_server_download_url }}"
    dest: "{{ code_server_lib_path }}"
    remote_src: yes
    owner: "{{ user }}"
    group: "{{ user }}"
  tags:
    - code-server
  
- name: Changing perm of "code-server", adding "+x"
  file:
    dest: "{{ code_server_lib_bin }}"
    mode: a+x
    owner: "{{ user }}"
    group: "{{ user }}"
  tags:
    - code-server

- name: Create symbolic link 
  file:
    src: "{{ code_server_lib_bin }}"
    dest: "{{ code_server_bin }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    state: link
  tags:
    - code-server

- name: Creates code-server directory
  file:
    path: "/home/{{ user }}/.code-server"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
  tags:
    - code-server

- name: code-server | template /etc/systemd/system/code-server.service
  template: src=systemd.conf.j2 dest=/etc/systemd/system/code-server.service owner=root group=root mode=0755
  become: yes
  notify: restart code-server
  tags:
    - code-server